export const REQUEST_UPLOAD_FILE = 'REQUEST_UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

export const REQUEST_GET_USER_FILES = 'REQUEST_USER_FILES';
export const GET_USER_FILES_SUCCESS = 'GET_USER_FILES_SUCCESS';
export const GET_USER_FILES_FAILED = 'GET_USER_FILES_FAILED';
export const FILTER_USER_FILES = 'FILTER_USER_FILES';

export const REQUEST_DOWNLOAD_USER_FILE = 'REQUEST_DOWNLOAD_USER_FILE';
export const DOWNLOAD_USER_FILE_SUCCESS = 'DOWNLOAD_USER_FILE_SUCCESS';
export const DOWNLOAD_USER_FILE_FAILED = 'DOWNLOAD_USER_FILE_FAILED';

export const REQUEST_DELETE_FILE = 'REQUEST_DELETE_FILE';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_FAIL = 'DELETE_FILE_FAIL';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
