export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

export const APPLICATION_IS_STARTING = 'APPLICATION_IS_STARTING';
export const APPLICATION_STARTED = 'APPLICATION_STARTED';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
